// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/14/2025, 8:00:19 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/plugins/**/*.{js,ts,mjs}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/composables/**/*.{js,ts,mjs}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/utils/**/*.{js,ts,mjs}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/iputudickysundara/project/crypto/IgniteAI-static-website-design/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;